### ISSUE TITLE
Scrivener Ecto Doesn't Compile with Ecto 3.0-rc

### ISSUE THREAD

**Issue by geofflane** [mojotech/scrivener_ecto#62]
```
==> scrivener_ecto
Compiling 2 files (.ex)

== Compilation error in file lib/scrivener/paginater/ecto/query.ex ==
** (Ecto.Query.CompileError) unbound variable `x` in query. If you are attempting to interpolate a value, use ^var
    expanding macro: Ecto.Query.select/3
    lib/scrivener/paginater/ecto/query.ex:55: Scrivener.Paginater.Ecto.Query.prepare_select/1
    (elixir) expanding macro: Kernel.|>/2
    lib/scrivener/paginater/ecto/query.ex:55: Scrivener.Paginater.Ecto.Query.prepare_select/1
```

This syntax looks like it probably conflicts with the new named binding syntax in Ecto 3.

**Comment by drewolson** [comment]
I believe this is fixed in https://github.com/drewolson/scrivener_ecto/pull/60. I'm waiting to merge this until 3.0 is released.

**Comment by geofflane** [comment]
Sorry, I missed that PR

**Comment by drewolson** [comment]
Fixed on master
